# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'PusherDemo' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for PusherDemo
  pod 'Alamofire'
   pod 'PusherSwift'
   pod 'JSQMessagesViewController'
  target 'PusherDemoTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'PusherDemoUITests' do
    # Pods for testing
  end

end
